print("Hello World")
print('Python is fun')
print("""Life is too short, You need python""")
print('''Life is too short, You need python''')
print('"Python is very easy." he said.')
print("\"Python is very easy.\" he said.")
print("Life is too short\nYou need python")
print('''Life is too short
You need python2''')
head = "Python"
tail = " is fun"
print(head + tail)
print(head * 2)
print(len(head))
print(head[0])
print(head[0:3])
print(head[0:61])
print(head[2:])
print(head[:3])
print("I eat %d apples" % 3)
print("I ate %d apples. so I was sick %s days." % (10, "two"))
print("I eat {0} apples".format(4))
y = 3.42134234
print("{0:0.4f}".format(y))
print("{{ and }}".format())
print(f'나의 이름은 {head}. 나이는 {tail} 입니다.')
print(f'나의 이름은 {y + 1}. 나이는 {tail} 입니다.')
d = {'name': '홍길동', 'age': 30}
print(f'이름은 {d["name"]}. 나이는 {d["age"]} 이다.')
print(f'{"hi":=^10}')
print(head.count('t'))
aa = "python is the best choice"
print(aa.find('b'))
print(aa.find('k'))
print(aa.index('i'))
print(",".join('abcd'))
print(",".join(['a','b','c','d']))
print(head.upper())
print(head.lower())
print(" hi ".lstrip())
print(" hi ".rstrip())
print(" hi ".strip())
print("Life is too short".replace("Life", "Your leg"))
print("Life is too short".split())
print("Life is too short".split()[0])

